import 'package:flutter_test/flutter_test.dart';
import 'package:mockito/mockito.dart';
import 'package:mockito/annotations.dart';
import 'package:inventory/providers/inventory_provider.dart';
import 'package:inventory/models/inventory_item.dart';
import 'package:inventory/models/product.dart';
import 'package:inventory/services/inventory_service.dart';
import 'integration_test.mocks.dart'; // Generated by mockito

@GenerateMocks([InventoryService])
void main() {
  late InventoryProvider provider;
  late MockInventoryService mockService;

  setUp(() {
    mockService = MockInventoryService();
    provider = InventoryProvider.forTesting(mockService);
  });

  test('Complete inventory management flow', () async {
    // Mock empty initial data
    when(mockService.getAllInventoryItems()).thenAnswer((_) async => []);
    when(mockService.getAllProducts()).thenAnswer((_) async => []);
    await provider.loadInventoryItems();
    await provider.loadProducts();

    // Add a test item 
    final testItem = InventoryItem(
      id: DateTime.now().millisecondsSinceEpoch.toString(),
      name: 'Integration Test Item',
      description: 'Test Description',
      quantity: 10.0,
      unit: 'pcs',
      costPerUnit: 2.0,
      sellingPricePerUnit: 3.0,
      dateAdded: DateTime.now(),
      category: 'Test Category',
    );
    
    // Mock the add operation
    when(mockService.addInventoryItem(testItem)).thenAnswer((_) async => true);
    await provider.addInventoryItem(testItem);
    
    // Verify the item was added by checking if the service was called
    verify(mockService.addInventoryItem(testItem)).called(1);
    
    // Update the item by creating a new object with the same ID
    final updatedItem = InventoryItem(
      id: testItem.id,
      name: testItem.name,
      description: testItem.description,
      quantity: 15.0, // Updated value
      unit: testItem.unit,
      costPerUnit: testItem.costPerUnit,
      sellingPricePerUnit: testItem.sellingPricePerUnit,
      dateAdded: testItem.dateAdded,
      category: testItem.category,
      lowStockThreshold: testItem.lowStockThreshold,
    );
    
    // Mock the update operation
    when(mockService.updateInventoryItem(updatedItem)).thenAnswer((_) async => true);
    await provider.updateInventoryItem(updatedItem);
    
    // Verify the update was called
    verify(mockService.updateInventoryItem(updatedItem)).called(1);
  });

  test('Complete product management flow', () async {
    // Mock empty initial data
    when(mockService.getAllInventoryItems()).thenAnswer((_) async => []);
    when(mockService.getAllProducts()).thenAnswer((_) async => []);
    await provider.loadInventoryItems();
    await provider.loadProducts();

    // Add a test product
    final testProduct = Product(
      id: DateTime.now().millisecondsSinceEpoch.toString(),
      name: 'Integration Test Product',
      description: 'Test Product Description',
      sellingPrice: 25.0,
      components: [],
      dateCreated: DateTime.now(),
      category: 'Test Category',
    );
    
    // Mock the add operation
    when(mockService.addProduct(testProduct)).thenAnswer((_) async => true);
    await provider.addProduct(testProduct);
    
    // Verify the product was added
    verify(mockService.addProduct(testProduct)).called(1);
    
    // Update the product by creating a new object with the same ID
    final updatedProduct = Product(
      id: testProduct.id,
      name: testProduct.name,
      description: testProduct.description,
      sellingPrice: 30.0, // Updated value
      components: testProduct.components,
      dateCreated: testProduct.dateCreated,
      category: testProduct.category,
    );
    
    // Mock the update operation
    when(mockService.updateProduct(updatedProduct)).thenAnswer((_) async => true);
    await provider.updateProduct(updatedProduct);
    
    // Verify the update was called
    verify(mockService.updateProduct(updatedProduct)).called(1);
  });
  
  test('COGS calculation flow', () async {
    // Mock data for initial load
    when(mockService.getAllInventoryItems()).thenAnswer((_) async => []);
    when(mockService.getAllProducts()).thenAnswer((_) async => []);
    await provider.loadInventoryItems();
    await provider.loadProducts();

    // Add an inventory component item
    final componentItem = InventoryItem(
      id: 'component-${DateTime.now().millisecondsSinceEpoch}',
      name: 'Component Item',
      description: 'Component for testing',
      quantity: 100.0,
      unit: 'kg',
      costPerUnit: 2.0,
      sellingPricePerUnit: 3.0,
      dateAdded: DateTime.now(),
      category: 'Components',
    );

    // Mock the add operation
    when(mockService.addInventoryItem(componentItem)).thenAnswer((_) async => true);
    await provider.addInventoryItem(componentItem);

    // Update provider's internal list to include the new item for COGS calculation
    when(mockService.getAllInventoryItems()).thenAnswer((_) async => [componentItem]);
    await provider.loadInventoryItems(); // Reload to update internal list

    // Add a product that uses the component
    final productWithComponents = Product(
      id: 'product-${DateTime.now().millisecondsSinceEpoch}',
      name: 'Product with Components',
      description: 'Product for COGS test',
      sellingPrice: 50.0,
      components: [
        ProductComponent(
          inventoryItemId: componentItem.id,
          quantityNeeded: 2.0,
          unit: 'kg',
        ),
      ],
      dateCreated: DateTime.now(),
      category: 'Test Products',
    );

    // Mock the add operation
    when(mockService.addProduct(productWithComponents)).thenAnswer((_) async => true);
    await provider.addProduct(productWithComponents);

    // Update provider's internal list to include the new product
    when(mockService.getAllProducts()).thenAnswer((_) async => [productWithComponents]);
    await provider.loadProducts(); // Reload to update internal list

    // Calculate COGS for this product
    final cogs = provider.calculateProductCogs(productWithComponents.id);
    // Since we have 2.0 units needed of an item costing 2.0 per unit, COGS should be 4.0
    expect(cogs, 4.0);
  });
}