// Mocks generated by Mockito 5.4.6 from annotations
// in inventory/test/inventory_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:inventory/models/inventory_item.dart' as _i4;
import 'package:inventory/models/product.dart' as _i5;
import 'package:inventory/services/inventory_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [InventoryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockInventoryService extends _i1.Mock implements _i2.InventoryService {
  MockInventoryService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> addInventoryItem(_i4.InventoryItem? item) =>
      (super.noSuchMethod(
            Invocation.method(#addInventoryItem, [item]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateInventoryItem(_i4.InventoryItem? item) =>
      (super.noSuchMethod(
            Invocation.method(#updateInventoryItem, [item]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteInventoryItem(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteInventoryItem, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.InventoryItem>> getAllInventoryItems() =>
      (super.noSuchMethod(
            Invocation.method(#getAllInventoryItems, []),
            returnValue: _i3.Future<List<_i4.InventoryItem>>.value(
              <_i4.InventoryItem>[],
            ),
          )
          as _i3.Future<List<_i4.InventoryItem>>);

  @override
  _i3.Future<_i4.InventoryItem?> getInventoryItemById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getInventoryItemById, [id]),
            returnValue: _i3.Future<_i4.InventoryItem?>.value(),
          )
          as _i3.Future<_i4.InventoryItem?>);

  @override
  _i3.Future<void> addProduct(_i5.Product? product) =>
      (super.noSuchMethod(
            Invocation.method(#addProduct, [product]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateProduct(_i5.Product? product) =>
      (super.noSuchMethod(
            Invocation.method(#updateProduct, [product]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteProduct(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProduct, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.Product>> getAllProducts() =>
      (super.noSuchMethod(
            Invocation.method(#getAllProducts, []),
            returnValue: _i3.Future<List<_i5.Product>>.value(<_i5.Product>[]),
          )
          as _i3.Future<List<_i5.Product>>);

  @override
  _i3.Future<_i5.Product?> getProductById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getProductById, [id]),
            returnValue: _i3.Future<_i5.Product?>.value(),
          )
          as _i3.Future<_i5.Product?>);
}
