// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCgzt1XfUAGeo1JCgwru_BhD7dHBYUgzOA',
//     appId: '1:971754213314:web:9b8bf928fd556de0e2105b',
//     messagingSenderId: '971754213314',
//     projectId: 'inventory-pos-60940',
//     authDomain: 'inventory-pos-60940.firebaseapp.com',
//     storageBucket: 'inventory-pos-60940.firebasestorage.app',
//     measurementId: 'G-4ELM13EM0S',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCAnpU8U7pMJjiTBZuS9VfUDelCDkeYsQs',
//     appId: '1:971754213314:android:7f97e88240b58409e2105b',
//     messagingSenderId: '971754213314',
//     projectId: 'inventory-pos-60940',
//     storageBucket: 'inventory-pos-60940.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAAnFEgT6G39DLcTsdVB2MU5OFBkn6twdE',
//     appId: '1:971754213314:ios:6bf05356576166bee2105b',
//     messagingSenderId: '971754213314',
//     projectId: 'inventory-pos-60940',
//     storageBucket: 'inventory-pos-60940.firebasestorage.app',
//     iosBundleId: 'com.example.inventory',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAAnFEgT6G39DLcTsdVB2MU5OFBkn6twdE',
//     appId: '1:971754213314:ios:6bf05356576166bee2105b',
//     messagingSenderId: '971754213314',
//     projectId: 'inventory-pos-60940',
//     storageBucket: 'inventory-pos-60940.firebasestorage.app',
//     iosBundleId: 'com.example.inventory',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyCgzt1XfUAGeo1JCgwru_BhD7dHBYUgzOA',
//     appId: '1:971754213314:web:c12ea4a6655fc096e2105b',
//     messagingSenderId: '971754213314',
//     projectId: 'inventory-pos-60940',
//     authDomain: 'inventory-pos-60940.firebaseapp.com',
//     storageBucket: 'inventory-pos-60940.firebasestorage.app',
//     measurementId: 'G-8CDE90MB39',
//   );
// }
